name = "SeisRemoveEQ"
uuid = "ee8e518e-a107-11e9-1e00-0b6f0be20652"
authors = ["kurama"]
version = "0.1.0"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
ORCA = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SeisIO = "b372bb87-02dd-52bb-bcf6-c30dd83fd342"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
